### ISSUE TITLE
Setup Error!

### ISSUE THREAD

**Issue by ElfenTroll** [ophian/styx#20]
Hello,

If I run the installation of the current version with a valid token, a 500 error page always comes up after entering the data and starting. Where could the problem be? THX

**Comment by ElfenTroll** [comment]
This Errorcode is coming:

[13-Mar-2022 12:29:19 Europe/Berlin] PHP Fatal error:  Uncaught mysqli_sql_exception: Unknown system variable 'storage_engine' in /home/www/serendipity/include/db/mysqli.inc.php:76
Stack trace:
#0 /home/www/serendipity/include/db/mysqli.inc.php(76): mysqli_query(Object(mysqli), 'SET storage_eng...')
#1 /home/www/serendipity/include/db/mysqli.inc.php(555): serendipity_db_query('SET storage_eng...')
#2 /home/www/serendipity/include/functions_installer.inc.php(174): serendipity_db_schema_import('create table st...')
#3 /home/www/serendipity/include/admin/installer.inc.php(376): serendipity_installDatabase('mysqli')
#4 /home/www/serendipity/serendipity_admin.php(303): require('/home/www/seren...')
#5 {main}
  thrown in /home/www/serendipity/include/db/mysqli.inc.php on line 76

**Comment by ophian** [comment]
Hi

Hm strange...
What kind of mysql engine do you use? Is it MariaDB  or Oracle MySQL ? And in which version ?
I would recommend using MariaDB !! Because eval Oracle is not a well known supporter of OpenSource !

But I assume you use it somehow in a version up from 5.7.5+.

> MySQL 5.7.x uses InnoDB by default, and has removed the storage_engine system variable

I am sorry I can't test this currently by myself with a Oracle Mysql since I try to avoid using it. But you can use default_storage_engine instead, I think.

So what you can do is, open up the mysqli file and search for 
https://github.com/ophian/styx/commit/41ec3b31a3f540eaf5233e9434187cbf97bc4956

The second, the else part is where you have to set
``` php
serendipity_db_query("SET default_storage_engine=MYISAM");
```
or 
``` php
serendipity_db_query("SET default_storage_engine=InnoDB");
```
Perhaps you try using the InnoDB frst and see if Styx can handle everything with it good enough. In special the emoji and utf8mb4 regarded things.

After that and some extended tests and maybe some further time you can inform me which case I should use to fix this for future Styx versions.

Thanks

**Comment by ElfenTroll** [comment]
Hi,

can you please look here: http://php.bloggernotizen.de  ... This is the configuration of my rented server, which I cannot change. It would be nice if you could tell me specifically what I should adjust where so that it works. thx

**Comment by ophian** [comment]
https://github.com/ophian/styx/blob/master/include/db/mysqli.inc.php#L555
replace with
``` php
serendipity_db_query("SET default_storage_engine=InnoDB");
```
... and remove the phpinfo quickly :)

**Comment by ElfenTroll** [comment]
Hi ophian,

now it worked! I was able to complete the installation. There was only one hint that mysqli.inc.php was damaged. But the installation was still carried out. I'll see how things are going and it would be nice if the reported problem was fixed in the next update.

Thanks again for your really quick help!!! The thread can now be closed, or do I have to close it?

Michael E.

**Comment by ophian** [comment]
Up to you... Glad it worked.
Have fun with Styx!  :)

**Comment by ElfenTroll** [comment]
Oh yeah... sorry for my bad english. I'm German and unfortunately I can't speak English very well. :-) :-)

**Comment by ophian** [comment]
Kein Problem!
Deutsch geht auch aber unter Berücksichtigung ("künftiger" english speaker) hat man sich auf solchen Foren generell geeinigt Englisch als default zu benutzen. Aber wo kein Kläger, da .... 
Übrigens ist die mysqli.inc.php jetzt nicht damaged, sondern nur verändert. Das ist alles.

**Comment by ophian** [comment]
I had to precise these fixes a little more, since Oracle MySQL with InnoDB up from 5.7 is able to handle the key length limits of older versions for utf8mb4 byte limits.
If you like to help, please drop your styx database (with phpMyAdmin or the tool you have) you had installed after our hotfix and replace `/include/db/mysqli.inc.php` and `/include/functions_installer.inc.php` with these 2 new fixed files. They show up in RAW format already, so all you need to do is right-save-click them to your computer and upload them to you hosts Styx envronment. Then nuke the `serendipity_config_local.inc.php file` and you can install again (like the first time).

https://raw.githubusercontent.com/ophian/styx/b1ccd2b1cec3c7ce5e6763d50e3789991433254c/include/db/mysqli.inc.php
https://raw.githubusercontent.com/ophian/styx/1b9109b4ab53e13c3de8f04b01aa8b373b60e345/include/functions_installer.inc.php

@ElfenTroll 
Ich musste diese Fixes noch ein wenig präzisieren, da Oracle MySQL mit InnoDB ab 5.7.x in der Lage ist, die Schlüssellängenbegrenzungen älterer Versionen für utf8mb4 Byte-Limits nun korrekt zu handhaben.
Wenn du helfen möchtest, lösche bitte deine Datenbank (mit phpMyAdmin oder dem Tool, das du hast), die du nach unserem Hotfix installiert hattest, und ersetzt die vorhandenen `/include/db/mysqli.inc.php` and `/include/functions_installer.inc.php` Dateien durch diese beiden neuen korrigierten Dateien. Sie liegen bereits im RAW-Format vor, so dass sie nur noch mit der rechten Maustaste auf deinem Computer gespeichert und in deine Styx Hostumgebung hochladen werden müssen. Dann lösche die Datei `serendipity_config_local.inc.php` im Styx root und du kannst alles erneut installieren (so wie beim ersten Mal). 
Das wäre natürlich toll, bevor du allzuviel in deines neues Projekt investierst hast, da wir damit gleich testen können, ob alles nun richtig richtig ist.

(Übrigens ist de phpinfo immer noch aktiv. Vielleicht liegt das am NGINX Cache und müsste definitiv überschrieben werden?)

**Comment by ElfenTroll** [comment]
Hallo Ian,

wegen Job dauert das alles immer etwas bei mir ... :-) Habe jetzt gerade komplett neu installiert und konnte zunächst keine Installationsfehler feststellen. Das Setup lief anstandslos mit den geänderten Dateien durch. Danke für den schnellen "Support" ... :-)

**Comment by ophian** [comment]
Super. Danke.
Kannst du bitte mit phpMyAdmin noch einen schnellen Gegencheck machen auf die styx_config Tabelle. Dort unter Struktur:
Tabellenstruktur von styx_config
Was genau steht unter bzw im PRIMARY key bei name? Hat das eine Klammer mit Zahlen?
so wie hier zB.
```
PRIMARY 	BTREE 	Ja 	Nein 	name (239) 		A 	Nein 	
					authorid 	90 	A 	Nein
```
Bei dir mit mysql 8 sollte for nur `name` stehen.

**Comment by ElfenTroll** [comment]
Hi,

so sieht es aus ...

![Ashampoo_Snap_Dienstag, 15  März 2022_15h51m52s](https://user-images.githubusercontent.com/101506660/158405187-e23dfa94-adc3-4ded-bd83-97a21dfb913d.png)

**Comment by ElfenTroll** [comment]
Puh, das hört sich kompliziert für einen DummDödel wie mich an ... :-) Ich lege das erst einmal noch zur Seite ... Wird das mit einem der nächsten Updates den dann automatisch korrigiert?!?

**Comment by ophian** [comment]
Nee das ist zu anfällig. Lass es einfach wie es ist. Es spielt nicht wirklich eine Rolle.
