### ISSUE TITLE
Removing tags

### ISSUE THREAD

**Issue by hbarel** [ophian/styx#51]
I wonder if anyone has had any issues with removing tags from existing posts.

When I use "edit entries" to edit an existing post, and then edit its tags to remove a tag or more, I can save and the entry is saved properly, but the tag is not really removed. It will still appear on the post, and if I edit the post again the tag re-emerges there as if it was never removed.

I use freetag 5.40.

**Comment by ophian** [comment]
Hi, Happy New Year!
I don't remember the reason - long ago - but there was one for this behaviour... I'll have to search for this deeply myself. I think it somehow had to do with the jquery.autocomplet tag javascript and the laziness of double request behaviour ...

In the mean time you can do this:
1. Delete the tag in the input field (including its belonging comma)
2. Then mark and copy all rest tags from the input field to keep in clipboard
3. Then check the checkbox to nuke *all* tags from this entry
4. Jump to top and save the entry. You get an edit jumplink for a complete new entry request. Click it.
5. Re-enter the tags from clipboard - jump up - and save

This should do it.

**Comment by hbarel** [comment]
Happy new year, and thanks for the wonderful work in maintaining Styx!

I followed your advice and it worked. Specifically, it is step #4 that did the trick. This is a step I did not try before. Thank you.

**Comment by ophian** [comment]
Fine. Yes, ...saving is essential 😊

It can as well be that a single tag delete by the multi-tag filled input field was never supported... I'll find out and put it on the list, if possible.

**Comment by hbarel** [comment]
> Fine. Yes, ...saving is essential 😊

I *did* save, just did not press the link to reload the page after saving.

> It can as well be that a single tag delete by the multi-tag filled input field was never supported... I'll find out and put it on the list, if possible.

It didn't work also for erasing all tags. To the best I could tell, it did not record any change, until I followed your instruction of pressing the jump-link after saving.

**Comment by ophian** [comment]
I have assumed this. Yes, that is essential also, since there are (db) places involved that don't run again on a submit post fallback to self, like for the entries list. This can happen with other configuration sets in other places too. Expect it everwhere where a db set is involved, which needs a complete new refresh to get the new data.
The jump link is just a reminding helper. You can as well choose the normal access by the sidebar links.

**Comment by hbarel** [comment]
Understood, thanks.

It seems as the db was not updated either (it was not just the display not reflecting recent changes), because the post did not change for other viewers as well.

**Comment by ophian** [comment]
Yepp, pretty sure it currently does work only with the "nuke all" check. I am on it for the singular tag removal by hand.

**Comment by ophian** [comment]
I just added support for single tag deletion including some help description. Submitting the Spartacus plugin will remove the current additional plugin XML, to test this immediately via Plugin Updates, unless you probably have to wait for tomorrow.
Thanks for the hint. It was not the autocomplete thing I had in mind. It just was not included to happen, ...to guess, because of this differing showup behaviour between POSTed new data and old stored data that needs a new call request. So removing all with re-adding some seemed the simpler way.

**Comment by hbarel** [comment]
Thanks, @ophian !

**Comment by ophian** [comment]
Close, as fixed.
